version: "3.8"

services:
  fastapi:
    build: .
    container_name: fastapi_webhook
    restart: always
    ports:
      - "8000:8000"
    env_file:
      - .env
    networks:
      - evolution-net

networks:
  evolution-net:
    external: true
